### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by StendProg** [swharden/QuickPlot#3]
~Error during nuget restore. Can't get package info for `QuickPlot.WinForms` project.~
Sorry wrong alarm. Reopen VS and it builds

**Comment by swharden** [comment]
... this sounds like a NuGet server or an internet issue? I installed it on a different computer just now with no trouble.

Not sure if it makes a difference, but I created a new Windows Forms App using .NET Framework (4.7.2) using the latest version of Visual Studio Community.

**Comment by swharden** [comment]
> Reopen VS and it builds

lol, this is the story of my life

**Comment by StendProg** [comment]
Another problem. `QuickPlot.Demos.WinForms` has some strange reference to `OpenTK.GLControl` package. It compiles, but crashes at runtime. 
Manualy instaling `OpenTK.GLControl` for `QuickPlot.Demos.WinForms` fix problem, but this should be in repo reference to not make it all time manualy.

**Comment by swharden** [comment]
> `QuickPlot.Demos.WinForms` has some strange reference to `OpenTK.GLControl` package. It compiles, but crashes at runtime.

This is the same package referenced by https://github.com/swharden/ScottPlot/pull/114/

I'm very surprised it crashes on your computer (it doesn't crash on mine).

> Manualy instaling `OpenTK.GLControl` for `QuickPlot.Demos.WinForms` fix problem, but this should be in repo reference to not make it all time manualy.

I don't think I understand what this means... How do you recommend I improve this problem?

**Comment by StendProg** [comment]
> This is the same package referenced by swharden/ScottPlot#114

It crashes not in designer. It crashes after program run, and exception told that can't find `OpenTK.GLControl`. But compiler find all reference and build it. This means strange.

> I don't think I understand what this means... How do you recommend I improve this problem?

Simpliest way manualy install package for that project, and add it to git (package reference file).
But it shoud grab all dependencies automaticaly from reference projects (`QuickPlot.WinForms`). Maybe at moment you add reference in demo project to  `QuickPlot.WinForms` it hasn't reference to `OpenTK.GLControl`. Maybe something other.
