### ISSUE TITLE
ReRender only subplot which user interact.

### ISSUE THREAD

**Issue by StendProg** [swharden/QuickPlot#4]
I set heavy load on one of subplot (20000 lines). This render not smooth. 
But other simple subplots interactions also go slow.
Maybe additional implement `Render subplot` function, and call it only  on interactions, and not rerender not changed subplots. Plot library knows which subplot interacting.

**Comment by swharden** [comment]
I really like this idea! You created #9 to demonstrate one way to do this. 

I favored an alternative method which passes a Subplot rather than a SKRect  d0fdf3b7f84e9ecd35c93d8796dc2a311212d903

**Comment by swharden** [comment]
https://github.com/swharden/QuickPlot/blob/0e7e2bca351ff5e789f542add82e27f6a8d6a5af/src/QuickPlot/Figure.cs#L59-L80

**Comment by StendProg** [comment]
Notice that you can get unexpected `OnPaint` call with clipRectangle specified at any time. This call come from operating system or from application which host user control. Solution you provided do correct, but full redraw in this case. #9 redraw only subplots affected by clipRect param.

This scenarios very rare. Moving window outside screen and when move it back. Or the same unhiding user control from application it hosted by (user control may not be dock to main window).
Also quick plot works fast and in most scenarios there is no visible difference to full or partial render.

I can't explain why, but i also dislike sync call `Refresh()` instead of async `Invalidate`. The solution that you provided is required to use `Refresh()` only.

Solution you provided acceptable and looks simplier, just to notice you that it has some difference.
